<?php
require('inc/essentials.php'); // Include the file with helper functions
require('inc/db_config.php');  // Include the database configuration file
require('inc/vendor/autoload.php'); // Ensure TCPDF is autoloaded

if (isset($_GET['gen_pdf']) && isset($_GET['id'])) {
    $frm_data = filteration($_GET);

    // SQL query to retrieve bookings with the necessary JOIN and search conditions
    $query = "SELECT bo.*, bd.*, uc.email
    FROM `booking_order` bo 
    INNER JOIN `booking_details` bd ON bo.booking_id = bd.booking_id
    INNER JOIN `users` uc ON bo.user_id = uc.id
    WHERE ((bo.booking_status = 'booked' AND bo.arrival = '1') 
    OR (bo.booking_status = 'canceled' AND bo.refund = 1) 
    OR (bo.booking_status = 'Payment failed'))
    AND bo.booking_id = '$frm_data[id]'";

    $res = mysqli_query($con, $query);

    // Check if query executed successfully
    if (!$res) {
        die('Query Error: ' . mysqli_error($con));
    }

    $total_rows = mysqli_num_rows($res); // Get the total number of rows

    // Check if the result set is empty
    if ($total_rows == 0) {
        // Output an informative message and redirect if no rows are found
        echo "No data found for the specified booking ID.";
        exit; // Stop further processing
    }

    $data = mysqli_fetch_assoc($res);

    // Check if $data is set and not null
    if (!$data) {
         echo "Error fetching data.";
        exit; // Stop further processing
     }

     // Ensure that the price is set and is a valid number
        if (isset($data['price']) && is_numeric($data['price'])) {
            $price = $data['price'];
        } else {
            $price = 0; // Fallback value if the price is not set or invalid
       }


    // Format the dates
    $date = date("h:i A d-m-Y", strtotime($data['datetime'])); // Format the booking date
    $checkin = date("d-m-Y", strtotime($data['check_in'])); // Format the check-in date
    $checkout = date("d-m-Y", strtotime($data['check_out'])); // Format the check-out date

    // Generate the table data for the booking receipt
    $table_data = "
        <h2>Booking Receipt</h2>
        <table border='1' cellpadding='10' cellspacing='0'>
            <tr> 
                <td><strong>Order ID:</strong> {$data['order_id']}</td>
                <td><strong>Booking Date:</strong> $date</td>
            </tr>
            <tr>
                <td colspan='2'><strong>Status:</strong> {$data['booking_status']}</td>
            </tr>
            <tr>
                <td><strong>Name:</strong> {$data['user_name']}</td>
                <td><strong>Email:</strong> {$data['email']}</td>
            </tr>
            <tr>
                <td><strong>Phone No:</strong> {$data['phone_no']}</td>
                <td><strong>Address:</strong> {$data['address']}</td>
            </tr>
            <tr>
                <td><strong>Room Name:</strong> {$data['room_name']}</td>
                <td><strong>Price:</strong> $price per night</td>
            </tr>
            <tr>
                <td><strong>Check-in:</strong> $checkin</td>
                <td><strong>Check-out:</strong> $checkout</td>
            </tr>
    ";

    // Conditionally add more rows based on the booking status
    if ($data['booking_status'] == 'canceled') {
        $refund = ($data['refund']) ? "Amount Refunded" : "Not Refunded";
        $table_data .= "
            <tr>
                <td><strong>Amount Paid:</strong> {$data['trans_amount']}</td>
                <td><strong>Refund:</strong> $refund</td>
            </tr>";
    } elseif ($data['booking_status'] == 'Payment failed') {
        $table_data .= "
            <tr>
                <td><strong>Transaction Amount:</strong> {$data['trans_amount']}</td>
                <td><strong>Failure Response:</strong> {$data['trans_res_message']}</td>
            </tr>";
    } else {
        $table_data .= "
            <tr>
                <td><strong>Room Number:</strong> {$data['room_no']}</td>
                <td><strong>Amount Paid:</strong> {$data['trans_amount']}</td>
            </tr>";
    }

    // Close the table
    $table_data .= "</table>";

    // PDF generation using TCPDF
    $pdf = new \TCPDF();

    // Set document information
    $pdf->SetCreator(PDF_CREATOR);
    $pdf->SetAuthor('Your Name');
    $pdf->SetTitle('Booking Receipt');
    $pdf->SetSubject('TCPDF Tutorial');
    $pdf->SetKeywords('TCPDF, PDF, example, test, guide');

    // Set default header data (optional)
    $pdf->SetHeaderData('', 0, 'Booking Receipt', 'Generated by Your Application');

    // Set header and footer fonts
    $pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

    // Set default font subsetting mode
    $pdf->setFontSubsetting(true);

    // Set default font
    $pdf->SetFont('helvetica', '', 12);

    // Add a page
    $pdf->AddPage();

    // Write the HTML content to the PDF
    $pdf->writeHTML($table_data, true, false, true, false, '');

    // Close and output PDF document
    $pdf->Output('booking_receipt.pdf', 'D');
} else {
    header('location: dashboard.php');
}


?>